amazon:
  service: S3
  access_key_id: tnsryantsuyran
  secret_access_key: tnusyrantuysrna
  region: utnsryantra
  bucket: ntuysranutysnray

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>
