amazon:
  service: S3
  access_key_id: 'invalid' 
  secret_access_key: 'invalid'
  region: <%= ENV['S3_REWARDS_BUCKET_REGION'] %>
  bucket: <%= ENV['S3_REWARDS_BUCKET_NAME'] %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>
